plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'profect.goorm1'
version = '0.0.1-SNAPSHOT'
description = 'stat-service'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {

    // spring-boot-starters
    implementation 'org.springframework.boot:spring-boot-starter-batch'

    // Database
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'com.h2database:h2'
    testImplementation 'com.h2database:h2'

    // Utilities
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Observability
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-otlp'
}

tasks.named('test') {
    useJUnitPlatform()
}
