server:
  port: ${SERVER_PORT}

spring:
  application:
    name: stat-service

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.springframework.batch: INFO
      org.springframework.jdbc: DEBUG
      org.springframework.boot.actuate.autoconfigure.tracing: DEBUG
      io.micrometer.tracing: DEBUG
      io.opentelemetry.exporter.otlp: DEBUG


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  prometheus:
    metrics:
      export:
        pushgateway:
          enabled: true
          push-rate: 5s

  otlp:
    logging:
      endpoint: http://localhost:4317
      transport: grpc

    tracing:
      endpoint: http://localhost:4317
      transport: grpc




